### ISSUE TITLE
cidpoint 알림톡 정규식 누락 추가

### ISSUE THREAD

**Issue by moonsungjun** [Taebu/safen_point#7]
![cidpoint_알림톡_페이지_1](https://user-images.githubusercontent.com/19964344/60695235-fe3f3780-9f1b-11e9-9328-a9a6c86d588b.jpg)

#{씨아이디포인트금액}

정규식 추가

![image](https://user-images.githubusercontent.com/19964344/60695101-7fe29580-9f1b-11e9-93f9-424254a17df1.png)

소비자 "point" 부분으로 표시

**Comment by Taebu** [comment]
~~씨아이디포인트금액~~

#{시아이디포인트금액}  = prq_store.cid_point
